/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as StandingsRouteImport } from './routes/standings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTournamentsRouteImport } from './routes/dashboard.tournaments'
import { Route as DashboardTeamsRouteImport } from './routes/dashboard.teams'
import { Route as DashboardPlayersRouteImport } from './routes/dashboard.players'
import { Route as DashboardMatchesRouteImport } from './routes/dashboard.matches'
import { Route as DashboardAuctionsRouteImport } from './routes/dashboard.auctions'
import { Route as DashboardAuctionsAuctionIdRouteImport } from './routes/dashboard.auctions.$auctionId'

const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsRoute = StandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTournamentsRoute = DashboardTournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamsRoute = DashboardTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlayersRoute = DashboardPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMatchesRoute = DashboardMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuctionsRoute = DashboardAuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuctionsAuctionIdRoute =
  DashboardAuctionsAuctionIdRouteImport.update({
    id: '/$auctionId',
    path: '/$auctionId',
    getParentRoute: () => DashboardAuctionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/players': typeof PlayersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/standings': typeof StandingsRoute
  '/teams': typeof TeamsRoute
  '/tournaments': typeof TournamentsRoute
  '/dashboard/auctions': typeof DashboardAuctionsRouteWithChildren
  '/dashboard/matches': typeof DashboardMatchesRoute
  '/dashboard/players': typeof DashboardPlayersRoute
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/dashboard/tournaments': typeof DashboardTournamentsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/auctions/$auctionId': typeof DashboardAuctionsAuctionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/players': typeof PlayersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/standings': typeof StandingsRoute
  '/teams': typeof TeamsRoute
  '/tournaments': typeof TournamentsRoute
  '/dashboard/auctions': typeof DashboardAuctionsRouteWithChildren
  '/dashboard/matches': typeof DashboardMatchesRoute
  '/dashboard/players': typeof DashboardPlayersRoute
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/dashboard/tournaments': typeof DashboardTournamentsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/auctions/$auctionId': typeof DashboardAuctionsAuctionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/players': typeof PlayersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/standings': typeof StandingsRoute
  '/teams': typeof TeamsRoute
  '/tournaments': typeof TournamentsRoute
  '/dashboard/auctions': typeof DashboardAuctionsRouteWithChildren
  '/dashboard/matches': typeof DashboardMatchesRoute
  '/dashboard/players': typeof DashboardPlayersRoute
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/dashboard/tournaments': typeof DashboardTournamentsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/auctions/$auctionId': typeof DashboardAuctionsAuctionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/players'
    | '/sitemap.xml'
    | '/standings'
    | '/teams'
    | '/tournaments'
    | '/dashboard/auctions'
    | '/dashboard/matches'
    | '/dashboard/players'
    | '/dashboard/teams'
    | '/dashboard/tournaments'
    | '/dashboard/'
    | '/dashboard/auctions/$auctionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/players'
    | '/sitemap.xml'
    | '/standings'
    | '/teams'
    | '/tournaments'
    | '/dashboard/auctions'
    | '/dashboard/matches'
    | '/dashboard/players'
    | '/dashboard/teams'
    | '/dashboard/tournaments'
    | '/dashboard'
    | '/dashboard/auctions/$auctionId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/players'
    | '/sitemap.xml'
    | '/standings'
    | '/teams'
    | '/tournaments'
    | '/dashboard/auctions'
    | '/dashboard/matches'
    | '/dashboard/players'
    | '/dashboard/teams'
    | '/dashboard/tournaments'
    | '/dashboard/'
    | '/dashboard/auctions/$auctionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  PlayersRoute: typeof PlayersRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StandingsRoute: typeof StandingsRoute
  TeamsRoute: typeof TeamsRoute
  TournamentsRoute: typeof TournamentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tournaments': {
      id: '/dashboard/tournaments'
      path: '/tournaments'
      fullPath: '/dashboard/tournaments'
      preLoaderRoute: typeof DashboardTournamentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/teams': {
      id: '/dashboard/teams'
      path: '/teams'
      fullPath: '/dashboard/teams'
      preLoaderRoute: typeof DashboardTeamsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/players': {
      id: '/dashboard/players'
      path: '/players'
      fullPath: '/dashboard/players'
      preLoaderRoute: typeof DashboardPlayersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/matches': {
      id: '/dashboard/matches'
      path: '/matches'
      fullPath: '/dashboard/matches'
      preLoaderRoute: typeof DashboardMatchesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/auctions': {
      id: '/dashboard/auctions'
      path: '/auctions'
      fullPath: '/dashboard/auctions'
      preLoaderRoute: typeof DashboardAuctionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/auctions/$auctionId': {
      id: '/dashboard/auctions/$auctionId'
      path: '/$auctionId'
      fullPath: '/dashboard/auctions/$auctionId'
      preLoaderRoute: typeof DashboardAuctionsAuctionIdRouteImport
      parentRoute: typeof DashboardAuctionsRoute
    }
  }
}

interface DashboardAuctionsRouteChildren {
  DashboardAuctionsAuctionIdRoute: typeof DashboardAuctionsAuctionIdRoute
}

const DashboardAuctionsRouteChildren: DashboardAuctionsRouteChildren = {
  DashboardAuctionsAuctionIdRoute: DashboardAuctionsAuctionIdRoute,
}

const DashboardAuctionsRouteWithChildren =
  DashboardAuctionsRoute._addFileChildren(DashboardAuctionsRouteChildren)

interface DashboardRouteChildren {
  DashboardAuctionsRoute: typeof DashboardAuctionsRouteWithChildren
  DashboardMatchesRoute: typeof DashboardMatchesRoute
  DashboardPlayersRoute: typeof DashboardPlayersRoute
  DashboardTeamsRoute: typeof DashboardTeamsRoute
  DashboardTournamentsRoute: typeof DashboardTournamentsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAuctionsRoute: DashboardAuctionsRouteWithChildren,
  DashboardMatchesRoute: DashboardMatchesRoute,
  DashboardPlayersRoute: DashboardPlayersRoute,
  DashboardTeamsRoute: DashboardTeamsRoute,
  DashboardTournamentsRoute: DashboardTournamentsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  PlayersRoute: PlayersRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StandingsRoute: StandingsRoute,
  TeamsRoute: TeamsRoute,
  TournamentsRoute: TournamentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
